### ISSUE TITLE
SliceTracker does not appear in the module menu after installation on Linux

### ISSUE THREAD

**Issue by tokjun** [SlicerProstate/SliceTracker#220]
I installed SlicerTracker from Extensions Manager on Slicer  4.5.0-2016-09-28 on Ubuntu Linux 14.04 LTS. However, it did not appear in the module menu even after restarting the Slicer. The Python console showed the following message:

~~~
>>> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/develop/.config/NA-MIC/Extensions-25401/SliceTracker/lib/Slicer-4.5/qt-scripted-modules/SliceTracker.py", line 14, in <module>
    from SlicerProstateUtils.buttons import *
ImportError: No module named SlicerProstateUtils.buttons
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/develop/.config/NA-MIC/Extensions-25401/SliceTracker/lib/Slicer-4.5/qt-scripted-modules/SliceTrackerRegistration.py", line 4, in <module>
    from SlicerProstateUtils.mixins import ModuleLogicMixin, ModuleWidgetMixin
ImportError: No module named SlicerProstateUtils.mixins
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/develop/.config/NA-MIC/Extensions-25401/SliceTracker/lib/Slicer-4.5/qt-scripted-modules/SliceTrackerZFrameRegistration.py", line 7, in <module>
    from SlicerProstateUtils.mixins import ModuleLogicMixin, ModuleWidgetMixin
ImportError: No module named SlicerProstateUtils.mixins
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/develop/.config/NA-MIC/Extensions-25401/mpReview/lib/Slicer-4.5/qt-scripted-modules/mpReview.py", line 12, in <module>
    from SlicerProstateUtils.mixins import ModuleWidgetMixin, ModuleLogicMixin
ImportError: No module named SlicerProstateUtils.mixins
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/develop/.config/NA-MIC/Extensions-25401/mpReview/lib/Slicer-4.5/qt-scripted-modules/mpReviewPreprocessor.py", line 5, in <module>
    from SlicerProstateUtils.mixins import ModuleWidgetMixin
ImportError: No module named SlicerProstateUtils.mixins
~~~

**Comment by che85** [comment]
yesterday I added an icon to SlicerProstate, but I forgot to add the icon itself to git. Will be available with the next nightly build. Sorry for that
