### ISSUE TITLE
SliceTracker does not work on 4.11.20200930

### ISSUE THREAD

**Issue by tokjun** [SlicerProstate/SliceTracker#358]
SliceTracker does not load on the new release (4.11.20200930). 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/junichi/slicer/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/junichi/.config/NA-MIC/Extensions-29402/DeepInfer/lib/Slicer-4.11/qt-scripted-modules/DeepInfer.py", line 1, in <module>
    import Queue
ModuleNotFoundError: No module named 'Queue'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/junichi/slicer/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/junichi/.config/NA-MIC/Extensions-29402/SliceTracker/lib/Slicer-4.11/qt-scripted-modules/SliceTracker.py", line 6, in <module>
    from SliceTrackerUtils.configuration import SliceTrackerConfiguration
  File "/home/junichi/.config/NA-MIC/Extensions-29402/SliceTracker/lib/Slicer-4.11/qt-scripted-modules/SliceTrackerUtils/configuration.py", line 1, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/junichi/slicer/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/junichi/.config/NA-MIC/Extensions-29402/SliceTracker/lib/Slicer-4.11/qt-scripted-modules/SliceTrackerRegistration.py", line 309
    raise AttributeError, "File not found: %s" % inputFile
                        ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/junichi/slicer/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/junichi/.config/NA-MIC/Extensions-29402/SliceTracker/lib/Slicer-4.11/qt-scripted-modules/SurfaceCutToLabel.py", line 11, in <module>
    from SegmentEditorSurfaceCutLib import SurfaceCutLogic
  File "/home/junichi/.config/NA-MIC/Extensions-29402/SegmentEditorExtraEffects/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorSurfaceCutLib/__init__.py", line 4, in <module>
    from SegmentEditorEffect import *
ModuleNotFoundError: No module named 'SegmentEditorEffect'
TypeError: module.__init__() argument 1 must be str, not qSlicerScriptedLoadableModule

```
See also 
https://discourse.slicer.org/t/slicetracker-module-cannot-be-loaded-on-slicer-4-11-20200930/13895

**Comment by tokjun** [comment]
The module is working with a4e30e4 and QIICR/SlicerDevelopmentToolbox@fad9658 but has some limitations:
- The DeepInfer module causes an error while loading the SliceTracker module. The python 3 branch (https://github.com/DeepInfer/Slicer-DeepInfer/tree/python3) needs to be used. Also, as the current DeepInfer (DeepInfer/Slicer-DeepInfer@650459f) is not fully functional, the "Use_Deep_Learning" option must be turned off to prevent the module from calling DeepInfer. 
- "No preoperative images available" should be selected on the "Receiving image data" pop-up. The mpReview module (SlicerProstate/mpReview@8325c20) seems to have some issue. tokjun/mpReview@b20fff8 fixes some image loading issue, but needs more work.
